// <auto-generated>
// Rewired Constants
// This list was generated on 5/21/2020 2:02:14 PM
// The list applies to only the Rewired Input Manager from which it was generated.
// If you use a different Rewired Input Manager, you will have to generate a new list.
// If you make changes to the exported items in the Rewired Input Manager, you will
// need to regenerate this list.
// </auto-generated>

namespace RewiredConsts {
    public static partial class Action {
        // Default
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Left")]
        public const int Left = 15;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Right")]
        public const int Right = 16;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Up")]
        public const int Up = 17;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Down")]
        public const int Down = 18;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Submit")]
        public const int Submit = 19;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Cancel")]
        public const int Cancel = 20;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "PickUp")]
        public const int PickUp = 21;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "ChangeMoveState")]
        public const int ChangeMoveState = 22;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "OpenBag")]
        public const int OpenBag = 23;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "OpenMission")]
        public const int OpenMission = 24;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "OpenSetting")]
        public const int OpenSetting = 27;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "OpenHelp")]
        public const int OpenHelp = 28;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "StopTime")]
        public const int StopTime = 29;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Space")]
        public const int Space = 37;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Map")]
        public const int Map = 38;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "SkipProcess")]
        public const int SkipProcess = 39;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Survey")]
        public const int Survey = 41;
        // UI
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "UIHorizontal")]
        public const int UIHorizontal = 10;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "UIVertical")]
        public const int UIVertical = 11;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "UISubmit")]
        public const int UISubmit = 12;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "UICancel")]
        public const int UICancel = 13;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "UIOpenBag")]
        public const int UIOpenBag = 25;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "UIOpenMission")]
        public const int UIOpenMission = 26;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "UILeft")]
        public const int UILeft = 30;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "UIRight")]
        public const int UIRight = 31;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "UIUp")]
        public const int UIUp = 32;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "UIDown")]
        public const int UIDown = 33;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "UIDialogSkip")]
        public const int UIDialogSkip = 34;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "UISpace")]
        public const int UISpace = 36;
    }
    public static partial class Category {
        public const int Default = 0;
    }
    public static partial class Layout {
        public static partial class Joystick {
            public const int Default = 0;
        }
        public static partial class Keyboard {
            public const int Default = 0;
            public const int UILayout = 4;
        }
        public static partial class Mouse {
            public const int Default = 0;
        }
        public static partial class CustomController {
            public const int Default = 0;
        }
    }
    public static partial class Player {
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "System")]
        public const int System = 9999999;
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player0")]
        public const int Player0 = 0;
    }
    public static partial class CustomController {
        public static partial class CustomController_MobileTouch {
            public const int sourceId = 0;
            public const string name = "CustomController_MobileTouch";
            public static readonly System.Guid typeGuid = new System.Guid("0899d519-94e6-44fc-b6d6-b3fafaea7210");
            public static partial class Axis {
                public const int AxisX = 2;
                public const int AxisY = 3;
            }
            public static partial class Button {
                public const int ButtonL = 0;
                public const int ButtonR = 1;
            }
        }
    }
    public static partial class LayoutManagerRuleSet {
        public const int LayoutManager_Gameplay = 0;
        public const int LayoutManager_UI = 3;
    }
    public static partial class MapEnablerRuleSet {
    }
}
